/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mantenimiento.views;

import javax.swing.JFrame;

/**
 *
 * @author emaue
 */
public class InsertQuestionForm extends javax.swing.JDialog {

    /** Creates new form InsertQuestion */
    public InsertQuestionForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_category = new javax.swing.ButtonGroup();
        bt_type = new javax.swing.ButtonGroup();
        lb_question = new javax.swing.JLabel();
        tf_Question = new javax.swing.JTextField();
        lbb_category = new javax.swing.JLabel();
        rb_sports = new javax.swing.JRadioButton();
        rb_art = new javax.swing.JRadioButton();
        rb_entertaiment = new javax.swing.JRadioButton();
        rb_history = new javax.swing.JRadioButton();
        rb_geography = new javax.swing.JRadioButton();
        rb_science = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        rb_boolean = new javax.swing.JRadioButton();
        rb_uniqueSelection = new javax.swing.JRadioButton();
        rb_multipleSelection = new javax.swing.JRadioButton();
        bt_save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lb_question.setText("Texto de la pregunta:");

        lbb_category.setText("Categoría:");

        bg_category.add(rb_sports);
        rb_sports.setText("Deportes");

        bg_category.add(rb_art);
        rb_art.setText("Arte");

        bg_category.add(rb_entertaiment);
        rb_entertaiment.setText("Entretenimiento");

        bg_category.add(rb_history);
        rb_history.setText("Historia");

        bg_category.add(rb_geography);
        rb_geography.setText("Geografia");

        bg_category.add(rb_science);
        rb_science.setText("Ciencia");

        jLabel1.setText("Tipo de pregunta");

        bt_type.add(rb_boolean);
        rb_boolean.setText("Booleana");
        rb_boolean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_booleanActionPerformed(evt);
            }
        });

        bt_type.add(rb_uniqueSelection);
        rb_uniqueSelection.setText("Seleccion unica");
        rb_uniqueSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_uniqueSelectionActionPerformed(evt);
            }
        });

        bt_type.add(rb_multipleSelection);
        rb_multipleSelection.setText("Seleccion multiple");

        bt_save.setText("Guardar");
        bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rb_history)
                        .addGap(18, 18, 18)
                        .addComponent(rb_geography)
                        .addGap(18, 18, 18)
                        .addComponent(rb_science))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rb_sports)
                        .addGap(18, 18, 18)
                        .addComponent(rb_art)
                        .addGap(18, 18, 18)
                        .addComponent(rb_entertaiment))
                    .addComponent(lbb_category)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_question)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Question, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_save)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb_boolean)
                                .addGap(18, 18, 18)
                                .addComponent(rb_uniqueSelection)))
                        .addGap(18, 18, 18)
                        .addComponent(rb_multipleSelection)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_question)
                    .addComponent(tf_Question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbb_category)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_sports)
                    .addComponent(rb_art)
                    .addComponent(rb_entertaiment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_history)
                    .addComponent(rb_geography)
                    .addComponent(rb_science))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_boolean)
                    .addComponent(rb_uniqueSelection)
                    .addComponent(rb_multipleSelection))
                .addGap(36, 36, 36)
                .addComponent(bt_save)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveActionPerformed
        String question = tf_Question.getText();
        String category = "";
        String type = "";
        
        if (rb_sports.isSelected()) {
            category = "Deportes";
        } else if (rb_art.isSelected()) {
            category = "Arte"; 
        } else if (rb_entertaiment.isSelected()) {
            category = "Entretenimiento";
        } else if (rb_history.isSelected()) {
            category = "Historia";
        } else if (rb_geography.isSelected()) {
            category = "Geografia";
        } else if (rb_science.isSelected()) {
            category = "Ciencia";
        }
        
        if (rb_boolean.isSelected()) {
            type = "Booleana";
        } else if (rb_uniqueSelection.isSelected()) {
            type = "Seleccion unica"; 
        } else if (rb_multipleSelection.isSelected()) {
            type = "Seleccion multiple";
        }
        this.dispose();
    }//GEN-LAST:event_bt_saveActionPerformed

    private void rb_booleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_booleanActionPerformed
        QuestionBooleanForm questionboolean = new QuestionBooleanForm((JFrame)this.getParent(), true);
        questionboolean.setVisible(true);
    }//GEN-LAST:event_rb_booleanActionPerformed

    private void rb_uniqueSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_uniqueSelectionActionPerformed
        UniqueSelectionForm uniqueselection = new UniqueSelectionForm((JFrame)this.getParent(), true);
        uniqueselection.setVisible(true);
    }//GEN-LAST:event_rb_uniqueSelectionActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_category;
    private javax.swing.JButton bt_save;
    private javax.swing.ButtonGroup bt_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_question;
    private javax.swing.JLabel lbb_category;
    private javax.swing.JRadioButton rb_art;
    private javax.swing.JRadioButton rb_boolean;
    private javax.swing.JRadioButton rb_entertaiment;
    private javax.swing.JRadioButton rb_geography;
    private javax.swing.JRadioButton rb_history;
    private javax.swing.JRadioButton rb_multipleSelection;
    private javax.swing.JRadioButton rb_science;
    private javax.swing.JRadioButton rb_sports;
    private javax.swing.JRadioButton rb_uniqueSelection;
    private javax.swing.JTextField tf_Question;
    // End of variables declaration//GEN-END:variables

}
